### ISSUE TITLE
Docs not found on pursuit

### ISSUE THREAD

**Issue by dvdsgl** [hdgarrood/purescript-sequences#29]
Following your documentation links leads to a page with:

![image](https://user-images.githubusercontent.com/108197/28327402-2392bc46-6b98-11e7-9fbb-b46447783761.png)

**Comment by hdgarrood** [comment]
I've just published 1.0.3 whose docs are up now. I don't think I'll bother with previous versions, though, since they don't compile with 0.11.x and that means that it's a bit of a faff. Thanks for the report though!
