### ISSUE TITLE
Is there any reason this isn't in the spago package set?

### ISSUE THREAD

**Issue by ursi** [hdgarrood/purescript-sequences#35]
https://github.com/purescript/package-sets/blob/master/src/groups/hdgarrood.dhall

**Comment by hdgarrood** [comment]
Yes:
* I expect it would end up being dropped, because I don't provide timely updates
* I don't really recommend this package very strongly these days at all, because I haven't yet come across any real-life scenario where it actually offered an improvement over Array.
