### ISSUE TITLE
Error during compilation (purescript 0.14.1)

### ISSUE THREAD

**Issue by Swordlash** [hdgarrood/purescript-sequences#37]
Hi,

After adding project to the `packages.dhall` (why isn't sequences in spago package set?) and running `spago build`, I got the following error:
```
Error found:
at .spago/sequences/v2.1.0/src/Data/Sequence/NonEmpty.purs:233:1 - 235:64 (line 233, column 1 - line 235, column 64)

  The following type class members have not been implemented:
  foldr1 :: forall a. (a -> a -> a) -> Seq a -> a
  foldl1 :: forall a. (a -> a -> a) -> Seq a -> a

in type class instance
                                       
  Data.Semigroup.Foldable.Foldable1 Seq
```

Removing this file manually from `.spago` directory fixed the issue (I don't use `NonEmpty` in my project).

**Comment by hdgarrood** [comment]
`sequences` is not in the package set because it is teetering on the edge of being unmaintained. I'd accept a PR to get it compiling with v0.14.1 again but I'm unlikely to do it myself.

**Comment by Swordlash** [comment]
Sorry, I took the last release version instead of the last commit. It works fine then.

**Comment by hdgarrood** [comment]
Oh, I should just cut another release then.

**Comment by hdgarrood** [comment]
v3.0.2 is out
